apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
  namespace: orders-api
data:
  POSTGRES_HOST: "orders-server-postgresql.orders-api.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "server"
  POSTGRES_USER: "orders"
